services:
  planner-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEFAULT_MODEL=gpt-4o-mini
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=planner-bot-dev
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=planner-bot
      - ENVIRONMENT=development
    depends_on:
      - otel-collector
    volumes:
      - ./app/memory:/app/app/memory
      - ./prompts:/app/prompts

  otel-collector:
    build:
      context: .
      dockerfile: Dockerfile.otel-collector
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_CLOUDWATCH_LOG_GROUP=${AWS_CLOUDWATCH_LOG_GROUP:-/aws/apprunner/planner-bot}
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro

networks:
  default:
    driver: bridge