# OTLP Collector Configuration for AWS CloudWatch Integration

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 256

  resource:
    attributes:
      - key: service.name
        value: planner-bot
        action: upsert
      - key: service.version
        value: 1.0.0
        action: upsert

exporters:
  # AWS CloudWatch Logs
  awscloudwatchlogs:
    region: ${AWS_REGION}
    log_group_name: ${AWS_CLOUDWATCH_LOG_GROUP}
    log_stream_name: planner-bot-traces

  # AWS CloudWatch Metrics (EMF)
  awsemf:
    region: ${AWS_REGION}
    namespace: PlannerBot
    dimension_rollup_option: NoDimensionRollup
    metric_declarations:
      - dimensions: [[service.name], [service.name, method]]
        metric_name_selectors:
          - ".*"

  # Debug logging
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [awscloudwatchlogs, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [awsemf, logging]

  extensions: []